[network]
name = "testnet"
node_rpc_address = "https://api.testnet.hiro.so"

[accounts.deployer]
# NEW SECURE TESTNET DEPLOYER - Generated 2025-08-18 - FUNDED ✅
mnemonic = "shuffle muffin remove sphere laugh crop length zoo frown three donkey cage reward weather season bless all joy area bridge drama smart police empower"
balance = 500000000  # FUNDED - Ready for deployment 

[accounts.wallet_1]  
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 50000000000

[accounts.wallet_2]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about" 
balance = 50000000000
