[network]
# Minimal network config to satisfy Clarinet parser during non-devnet commands.
# Values are placeholders; override when running clarinet devnet.
name = "devnet"
block_time = 3
rpc_bind = "127.0.0.1:20443"

[accounts.deployer]
# Test-only mnemonic for local devnet. Do NOT use on real networks.
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 1000000000000000

[accounts.wallet_1]
mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon about"
balance = 500000000000000

[devnet]
disable_expensive_metrics = true
