[project]
name = "autovault"

[contracts.vault]
path = "contracts/vault.clar"

[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"

[contracts.mock-ft]
path = "contracts/mock-ft.clar"

[contracts.timelock]
path = "contracts/timelock.clar"

[contracts.gov-token]
path = "contracts/gov-token.clar"

[contracts.dao]
path = "contracts/dao.clar"

[contracts.registry]
path = "contracts/registry.clar"

[contracts.strategy-trait]
path = "contracts/traits/strategy-trait.clar"

[contracts.vault-admin-trait]
path = "contracts/traits/vault-admin-trait.clar"

[contracts.vault-trait]
path = "contracts/traits/vault-trait.clar"

[contracts.treasury]
path = "contracts/treasury.clar"

[contracts.analytics]
path = "contracts/analytics.clar"

[contracts.creator-token]
path = "contracts/creator-token.clar"

[contracts.dao-governance]
path = "contracts/dao-governance.clar"

[contracts.bounty-system]
path = "contracts/bounty-system.clar"
