[project]
name = "autovault"
description = "AutoVault DeFi protocol - clarinet config"
requirements = []

[accounts]
deployer = { mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art", balance = 10_000_000_000 }
wallet_1 = { mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art", balance = 5_000_000_000, derivation = 1 }
wallet_2 = { mnemonic = "abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon abandon art", balance = 5_000_000_000, derivation = 2 }

[network]
api_endpoint = "http://localhost:3999" # clarinet devnet default
delay_execution_start = false

[contracts.vault]
path = "contracts/vault.clar"
clarity_version = 2
epoch = "2.4"

[contracts.sip-010-trait]
path = "contracts/traits/sip-010-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.mock-ft]
path = "contracts/mock-ft.clar"
clarity_version = 2
epoch = "2.4"

[contracts.timelock]
path = "contracts/timelock.clar"
clarity_version = 2
epoch = "2.4"

[contracts.gov-token]
path = "contracts/gov-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dao]
path = "contracts/dao.clar"
clarity_version = 2
epoch = "2.4"

[contracts.registry]
path = "contracts/registry.clar"
clarity_version = 2
epoch = "2.4"

[contracts.strategy-trait]
path = "contracts/traits/strategy-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-admin-trait]
path = "contracts/traits/vault-admin-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.vault-trait]
path = "contracts/traits/vault-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.treasury]
path = "contracts/treasury.clar"
clarity_version = 2
epoch = "2.4"

[contracts.analytics]
path = "contracts/analytics.clar"
clarity_version = 2
epoch = "2.4"

[contracts.creator-token]
path = "contracts/creator-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dao-governance]
path = "contracts/dao-governance.clar"
clarity_version = 2
epoch = "2.4"


[contracts.dao-automation]
path = "contracts/dao-automation.clar"
clarity_version = 2
epoch = "2.4"

[contracts.bounty-system]
path = "contracts/bounty-system.clar"
clarity_version = 2
epoch = "2.4"

[contracts.automated-bounty-system]
path = "contracts/automated-bounty-system.clar"
clarity_version = 2
epoch = "2.4"

[contracts.avg-token]
path = "contracts/avg-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.avlp-token]
path = "contracts/avlp-token.clar"
clarity_version = 2
epoch = "2.4"

[contracts.pool-trait]
path = "contracts/pool-trait.clar"
clarity_version = 2
epoch = "2.4"

[contracts.math-lib]
path = "contracts/math-lib.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dex-factory]
path = "contracts/dex-factory.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dex-pool]
path = "contracts/dex-pool.clar"
clarity_version = 2
epoch = "2.4"

[contracts.dex-router]
path = "contracts/dex-router.clar"
clarity_version = 2
epoch = "2.4"

[contracts.mock-dex]
path = "contracts/mock-dex.clar"
clarity_version = 2
epoch = "2.4"

[contracts.enterprise-monitoring]
path = "contracts/enterprise-monitoring.clar"
clarity_version = 2
epoch = "2.4"

[contracts.multi-hop-router]
path = "contracts/multi-hop-router.clar"
clarity_version = 2
epoch = "2.4"

[contracts.stable-pool]
path = "contracts/stable-pool.clar"
clarity_version = 2
epoch = "2.4"

[contracts.weighted-pool]
path = "contracts/weighted-pool.clar"
clarity_version = 2
epoch = "2.4"

[contracts.circuit-breaker]
path = "contracts/circuit-breaker.clar"
clarity_version = 2
epoch = "2.4"

[contracts.oracle-aggregator]
path = "contracts/oracle-aggregator.clar"
clarity_version = 2
epoch = "2.4"

[contracts.state-anchor]
path = "contracts/state-anchor.clar"
clarity_version = 2
epoch = "2.4"




